### ISSUE TITLE
Prometheus能提供图片吗？

### ISSUE THREAD

**Issue by njkfei** [qunarcorp/qmq#33]
我看到可以通过Prometheus搭建监控环境，如果有图文，更容易理解．

**Comment by aapple** [comment]
## Prometheus监控QMQ说明文档

Prometheus是一个开源监控报警系统，不过本质上来说它就是一个时序列数据库(TSDB)，主要负责根据配置，从相应的数据源处拉取和存储监控metric数据，如果要对拉取到的数据做直观的可视化图表展示和分析，
还需要搭配Grafana使用。

#### 1. 根据QMQ文档说明引入监控所需的jar包https://github.com/qunarcorp/qmq/blob/master/docs/cn/monitor.md

#### 2. 安装Prometheus和Grafana，参考图文教程：https://www.hi-linux.com/posts/25047.html
官网的Prometheus详细安装说明：https://prometheus.io/docs/prometheus/latest/getting_started/
官网的Grafana详细安装说明：http://docs.grafana.org/installation/

如果docker部署的话，直接下载Prometheus和Grafana的标准镜像就可以。

#### 3. Prometheus配置QMQ的数据源
修改Prometheus的配置文件prometheus.yml，添加实时server和delay-server的数据源ip地址

```
scrape_configs:
- job_name: qmq-server
  static_configs:
  - targets: ['ip1:3333', 'ip2:3333']
- job_name: qmq-delay-server
  static_configs:
  - targets: ['ip1:3333', 'ip2:3333']
```
  
#### 4. Grafana配置Prometheus数据源
安装好Grafana以后访问其web面板，根据提示添加Prometheus数据源即可。

#### 5. Grafana上配置QMQ的监控面板
这里已经列出了各个Server的监控指标，根据自己的关注重点配置相应的指标进面板即可：https://github.com/qunarcorp/qmq/blob/master/docs/cn/monitor.md

#### 推荐配置

| Graph名称 | Metrics|
|---------|---------|
|实时Server延迟|messageSequenceLag|
|Delay Server延迟时间|delayTime|
|Delay Server接收消息QPS|irate(receivedMessagesCount{job='qmq-delay-server'}[2m])|
|Delay Server投递的消息量QPS|irate(scheduleDispatch[2m])|
|实时Server接收消息QPS|irate(receivedMessagesCount{job="qmq-server"}[2m])|
|Consumer拉取请求QPS|irate(pullRequestCount[2m])|

#### 最终效果
![p w3 r3r v8 q _6 sze](https://user-images.githubusercontent.com/1774212/51729957-b7b5f900-20b0-11e9-8e34-3b3694cec4ce.png)

**Comment by njkfei** [comment]
下面的配置，相当于需要在至少２台机器上配置运行，如果使用一台机器的话，只有最先启动的进程会bind　3333端口号．
```
scrape_configs:
- job_name: qmq-server
  static_configs:
  - targets: ['ip1:3333', 'ip2:3333']
- job_name: qmq-delay-server
  static_configs:
  - targets: ['ip1:3333', 'ip2:3333']
```
